dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- name: tikal-jenkinsx-spring-test1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: jx-ants-smashing-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: ants-smashing-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.2
